language: cpp
sudo: required
dist: trusty

git:
    depth: 5

before_install:
- source ./install.deps.sh

install:
- install_os_deps

script:
- echo "Configuration info:"
- export_compiler_vars
- ninja --version
- ./bootstrap.py --ci && ninja

notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/b864d553270a069d26c8
        on_success: change  # options: [always|never|change] default: always
        on_failure: always  # options: [always|never|change] default: always
        on_start: never     # options: [always|never|change] default: always
    email:
        on_success: change
        on_failure: change

matrix:
  include: 
    - os: linux
      env: COMPILER=g++-4.9 LUA_VERSION=lua52
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-4.9
          - g++-4.9
          - ninja-build
          - liblua5.2-dev

    # gcc-5
    - os: linux
      env: COMPILER=g++-4.9 LUA_VERSION=luajit51
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-4.9
          - g++-4.9
          - ninja-build
          - libluajit-5.1-dev

    # gcc-5
    - os: linux
      env: COMPILER=g++-5 LUA_VERSION=lua52
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-5
          - g++-5
          - ninja-build
          - liblua5.2-dev

    # gcc-5
    - os: linux
      env: COMPILER=g++-5 LUA_VERSION=luajit51
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-5
          - g++-5
          - ninja-build
          - libluajit-5.1-dev

    # clang
    - os: linux
      env:
        - LLVM_VERSION=3.5.0
        - LLVM_ARCHIVE_PATH=$HOME/clang+llvm.tar.xz
        - COMPILER=clang++
        - CPPFLAGS="-I $HOME/clang-$LLVM_VERSION/include/c++/v1"
        - CXXFLAGS=-lc++
        - PATH=$HOME/clang-$LLVM_VERSION/bin:$PATH
        - LD_LIBRARY_PATH=$HOME/clang-$LLVM_VERSION/lib:$LD_LIBRARY_PATH
        - LUA_VERSION=lua52
      before_install:
       - wget http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $LLVM_ARCHIVE_PATH
       - mkdir $HOME/clang-$LLVM_VERSION
       - tar xf $LLVM_ARCHIVE_PATH -C $HOME/clang-$LLVM_VERSION --strip-components 1
       - export PATH=$HOME/clang+llvm/bin:$PATH
       - source ./install.deps.sh
      compiler: clang
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-4.9
          - g++-4.9
          - ninja-build
          - liblua5.2-dev

    - os: linux
      env:
        - LLVM_VERSION=3.6.0
        - LLVM_ARCHIVE_PATH=$HOME/clang+llvm.tar.xz
        - COMPILER=clang++
        - CPPFLAGS="-I $HOME/clang-$LLVM_VERSION/include/c++/v1"
        - CXXFLAGS=-lc++
        - PATH=$HOME/clang-$LLVM_VERSION/bin:$PATH
        - LD_LIBRARY_PATH=$HOME/clang-$LLVM_VERSION/lib:$LD_LIBRARY_PATH
        - LUA_VERSION=lua52
      before_install:
       - wget http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $LLVM_ARCHIVE_PATH
       - mkdir $HOME/clang-$LLVM_VERSION
       - tar xf $LLVM_ARCHIVE_PATH -C $HOME/clang-$LLVM_VERSION --strip-components 1
       - export PATH=$HOME/clang+llvm/bin:$PATH
       - source ./install.deps.sh
      compiler: clang
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-4.9
          - g++-4.9
          - ninja-build
          - liblua5.2-dev

    - os: linux
      env:
        - LLVM_VERSION=3.6.0
        - LLVM_ARCHIVE_PATH=$HOME/clang+llvm.tar.xz
        - COMPILER=clang++
        - CPPFLAGS="-I $HOME/clang-$LLVM_VERSION/include/c++/v1"
        - CXXFLAGS=-lc++
        - PATH=$HOME/clang-$LLVM_VERSION/bin:$PATH
        - LD_LIBRARY_PATH=$HOME/clang-$LLVM_VERSION/lib:$LD_LIBRARY_PATH
        - LUA_VERSION=luajit51
      before_install:
       - wget http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $LLVM_ARCHIVE_PATH
       - mkdir $HOME/clang-$LLVM_VERSION
       - tar xf $LLVM_ARCHIVE_PATH -C $HOME/clang-$LLVM_VERSION --strip-components 1
       - export PATH=$HOME/clang+llvm/bin:$PATH
       - source ./install.deps.sh
      compiler: clang
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-4.9
          - g++-4.9
          - ninja-build
          - libluajit-5.1-dev

    - os: osx
      osx_image: xcode7
      compiler: gcc
      env: COMPILER=g++-4.9 LUA_VERSION=lua53

    - os: osx
      osx_image: xcode7
      compiler: gcc
      env: COMPILER=g++-5 LUA_VERSION=lua53

    - os: osx
      osx_image: xcode7
      compiler: gcc
      env: COMPILER=g++-5 LUA_VERSION=luajit

    - os: osx
      osx_image: xcode7
      compiler: clang
      env: COMPILER=appleclang LUA_VERSION=lua53

  allow_failures:
    - os: osx
      compiler: clang 
