shallow_clone: true

os:
  - Visual Studio 2015

environment:
  matrix:
  - TOOLSET: vs2012
  - TOOLSET: vs2013
  - TOOLSET: vs2015

configuration:
  - Debug
  - Release

install:
  tools\bin\windows\genie %TOOLSET%

build:
  project: .build/projects/$(TOOLSET)/bx.sln
