language: c

env:
  global:
    - LUAROCKS=2.2.0-rc1
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit

branches:
  only:
    - master

before_install:
  - bash .travis/setup_lua.sh
  - sudo pip install cpp-coveralls

install:
  - sudo luarocks make rockspecs/luafilesystem-cvs-3.rockspec CFLAGS="-O2 -fPIC -ftest-coverage -fprofile-arcs" LIBFLAG="-shared --coverage"

script: 
  - cd tests
  - sudo lua test.lua

after_success:
  - coveralls -b .. -r .. -E usr

notifications:
  email:
    on_success: change
    on_failure: always
