// license:BSD-3-Clause
// copyright-holders:Fabio Priuli
#ifndef MAME_BUS_A7800_A78_CARTS_H
#define MAME_BUS_A7800_A78_CARTS_H

#pragma once

#include "rom.h"
#include "xm.h"
#include "hiscore.h"
#include "cpuwiz.h"
#include "bankset.h"

static SLOT_INTERFACE_START(a7800_cart)
	SLOT_INTERFACE_INTERNAL("a78_rom",      A78_ROM)
	SLOT_INTERFACE_INTERNAL("a78_pokey",    A78_ROM_POKEY)
	SLOT_INTERFACE_INTERNAL("a78_sg",       A78_ROM_SG)
	SLOT_INTERFACE_INTERNAL("a78_sg_pokey", A78_ROM_SG_POKEY)
	SLOT_INTERFACE_INTERNAL("a78_sg_ram",   A78_ROM_SG_RAM)
	SLOT_INTERFACE_INTERNAL("a78_sg9",      A78_ROM_SG9)
	SLOT_INTERFACE_INTERNAL("a78_mram",     A78_ROM_MRAM)
	SLOT_INTERFACE_INTERNAL("a78_abs",      A78_ROM_ABSOLUTE)
	SLOT_INTERFACE_INTERNAL("a78_act",      A78_ROM_ACTIVISION)
	SLOT_INTERFACE_INTERNAL("a78_hsc",      A78_HISCORE)
	SLOT_INTERFACE_INTERNAL("a78_xm",       A78_XM)     // the actual XM expansion (as passthru)
	SLOT_INTERFACE_INTERNAL("a78_bankset_sg",            A78_ROM_BANKSET_SG)
	SLOT_INTERFACE_INTERNAL("a78_bankset_sg_bankram",    A78_ROM_BANKSET_SG_BANKRAM)
	SLOT_INTERFACE_INTERNAL("a78_bankset",           A78_ROM_BANKSET_ROM)
	SLOT_INTERFACE_INTERNAL("a78_bankset_bankram",           A78_ROM_BANKSET_BANKRAM)
	SLOT_INTERFACE_INTERNAL("a78_bankset_52k",           A78_ROM_BANKSET_ROM_52K)
	SLOT_INTERFACE_INTERNAL("a78_megacart", A78_ROM_MEGACART)
	SLOT_INTERFACE_INTERNAL("a78_versa",    A78_ROM_VERSABOARD)
	// cart variants with a POKEY at 0x0450 (typically a VersaBoard variant, or an homebrew pcb)
	SLOT_INTERFACE_INTERNAL("a78_p450_t0",  A78_ROM_P450)
	SLOT_INTERFACE_INTERNAL("a78_p450_t1",  A78_ROM_P450_POKEY)
	SLOT_INTERFACE_INTERNAL("a78_p450_t6",  A78_ROM_P450_SG_RAM)
	SLOT_INTERFACE_INTERNAL("a78_p450_ta",  A78_ROM_P450_SG9)
	SLOT_INTERFACE_INTERNAL("a78_p450_vb",  A78_ROM_P450_VB)
	SLOT_INTERFACE_INTERNAL("a78_bankset_p800",  A78_ROM_BANKSET_ROM_POK800)
	SLOT_INTERFACE_INTERNAL("a78_bankset_sg_p800",            A78_ROM_BANKSET_SG_POK800)
	SLOT_INTERFACE_INTERNAL("a78_bankset_sg_bankram_p800",    A78_ROM_BANKSET_SG_BANKRAM_POK800)
	SLOT_INTERFACE_INTERNAL("a78_bankset_bankram_p800",           A78_ROM_BANKSET_BANKRAM_POK800)
	SLOT_INTERFACE_INTERNAL("a78_bankset_52k_p4000",           A78_ROM_BANKSET_ROM_52K_POK4000)
	SLOT_INTERFACE_INTERNAL("a78_bankset_p4000",  A78_ROM_BANKSET_ROM_POK4000)
SLOT_INTERFACE_END


// supported devices
SLOT_INTERFACE_EXTERN(a78_cart);

#endif // MAME_BUS_A7800_A78_CARTS_H
